//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaxEntities : DbContext
    {
        public SinemaxEntities()
            : base("name=SinemaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BİLET> BİLET { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Filmler> Filmler { get; set; }
        public virtual DbSet<FilmResimleri> FilmResimleri { get; set; }
    }
}
